# Recomendación Juego


In [28]:
import pandas as pd
import os

path_reviews = os.path.join('..','data','clear','user_reviews.csv.gz')
path_steam_games = os.path.join('..','data','clear','steam_games.csv.gz')


## Carga de data

In [29]:
## Cargamos la data necesaria para solucionar este problema.

steam_colums = ['id','app_name','publisher','genres','price','developer','release_year']
# steam_colums = ['id','app_name','release_year']
steam_games = pd.read_csv(path_steam_games,usecols=steam_colums)

## renombraremos la columna id por steam_id
steam_games.rename(columns={'id':'steam_id'}, inplace=True)



# reviews_cols = ['item_id', 'recommend']
# reviews_cols = ['item_id', 'sentiment_analysis', 'recommend']
# user_reviews = pd.read_csv(path_reviews, compression='gzip',lineterminator='\n',usecols=reviews_cols)

## Preparación de data

In [4]:
# steam_reviews = steam_games.merge(user_reviews,
#                               left_on='steam_id', 
#                               right_on= 'item_id',
#                               how='inner').drop(columns=['steam_id','item_id'])

## Seleccion de las caracteristicas más importantes de un juego

In [35]:
import pandas as pd
from collections import Counter
from itertools import chain

def select_n_best(caracteristica, n):
    
    # Dividir las palabras en cada fila y contar la frecuencia de cada palabra
    conteo_palabras = Counter(chain.from_iterable(caracteristica.str.split(', ')))

    # Obtener las n palabras más comunes
    palabras_mas_comunes = conteo_palabras.most_common(n)

    print("Palabras más comunes:")
    for palabra, frecuencia in palabras_mas_comunes:
        print(f"{palabra}: {frecuencia}")
    
    return([palabras_mas_comunes[i][0] for i in range(n)])

In [36]:
steam_genres = steam_games['genres']

In [37]:
steam_developer = steam_games['developer']

## Preparacion del modelo

In [82]:
## Vamos a extraer en una lista las n palabras más importantes
n = 339

palabras_mas_relevantes = select_n_best(steam_genres, n)

text_palabras = (', ').join(palabras_mas_relevantes)

def drop_not_important(genres):
  return(', ').join([palabra for palabra in genres.split(', ') if palabra.capitalize() in palabras_mas_relevantes])


steam_games['genres'] = steam_games['genres'].apply(drop_not_important)

cols_concatenate = ['app_name','developer','genres']

steam_games['features'] = steam_games[cols_concatenate].apply(lambda row: ', '.join(row), axis=1)

steam_games['features']


Palabras más comunes:
Indie: 16783
Action: 12320
Casual: 9471
Adventure: 9344
Simulation: 7508
Strategy: 7289
RPG: 5552
Singleplayer: 4268
Multiplayer: 2283
Great Soundtrack: 2185
Free to Play: 2183
Puzzle: 2075
2D: 1915
Atmospheric: 1901
Early Access: 1839
VR: 1707
Sports: 1530
Platformer: 1420
Story Rich: 1417
Sci-fi: 1354
Fantasy: 1338
Difficult: 1289
Open World: 1273
Horror: 1269
Pixel Graphics: 1218
Racing: 1188
Shooter: 1178
Co-op: 1174
Massively Multiplayer: 1168
Female Protagonist: 1153
Anime: 1138
Funny: 1089
First-Person: 1037
Arcade: 958
Retro: 943
Sandbox: 937
Turn-Based: 932
FPS: 928
Comedy: 873
Point & Click: 855
Survival: 833
Classic: 787
Family Friendly: 754
Space: 708
Gore: 615
Third Person: 613
Movie: 601
Visual Novel: 585
Exploration: 582
Online Co-Op: 562
Cute: 542
Shoot 'Em Up: 526
Hidden Object: 517
Local Co-Op: 503
Local Multiplayer: 499
Rogue-like: 497
Zombies: 496
Tactical: 489
Utilities: 478
Violent: 464
RPGMaker: 462
Controller: 455
Design & Illustration: 454

0        Lost summoner kitty, Kotoshiro, Strategy, Acti...
1        Ironbound, Secret level srl, Strategy, Indie, ...
2        Real pool 3d - poolians, Poolians.com, Simulat...
3                 弹炸人2222, 彼岸领域, Action, Adventure, Casual
4        Log challenge, Otros, Action, Indie, Casual, S...
                               ...                        
29970    Colony on mars, Nikita "ghost_rus", Strategy, ...
29971    Logistical: south africa, Sacada, Strategy, In...
29972    Russian roads, Laush dmitriy sergeevich, Indie...
29973    Exit 2 - directions, Xropi,stev3ns, Indie, Cas...
29974    Maze run vr, Otros, Adventure, Indie, Action, ...
Name: features, Length: 29975, dtype: object

In [77]:
steam_games

publisher                                            genres  \
0             Kotoshiro       Strategy, Action, Indie, Casual, Simulation   
1      Making fun, inc.               Strategy, Indie, Fantasy, Difficult   
2          Poolians.com    Simulation, Sports, Casual, Indie, Multiplayer   
3                  彼岸领域                         Action, Adventure, Casual   
4                 Otros                     Action, Indie, Casual, Sports   
...                 ...                                               ...   
29970   Ghost_rus games               Strategy, Indie, Casual, Simulation   
29971            Sacada                           Strategy, Indie, Casual   
29972      Laush studio                         Indie, Simulation, Racing   
29973          Sixnails  Indie, Casual, Puzzle, Singleplayer, Atmospheric   
29974             Otros              Adventure, Indie, Action, Simulation   

                       app_name  price  steam_id                 developer  \
0           Lost summoner kitty   4.99  761140.0                 Kotoshiro   
1                     Ironbound   0.00  643980.0          Secret level srl   
2       Real pool 3d - poolians   0.00  670290.0              Poolians.com   
3                       弹炸人2222   0.99  767400.0                      彼岸领域   
4                 Log challenge   2.99  773570.0                     Otros   
...                         ...    ...       ...                       ...   
29970            Colony on mars   1.99  773640.0        Nikita "ghost_rus"   
29971  Logistical: south africa   4.99  733530.0                    Sacada   
29972             Russian roads   1.99  610660.0  Laush dmitriy sergeevich   
29973       Exit 2 - directions   4.99  658870.0             Xropi,stev3ns   
29974               Maze run vr   4.99  681550.0                     Otros   

       release_year                                           features  
0              2018  Lost summoner kitty, Kotoshiro, Strategy, Acti...  
1              2018  Ironbound, Secret level srl, Strategy, Indie, ...  
2              2017  Real pool 3d - poolians, Poolians.com, Simulat...  
3              2017           弹炸人2222, 彼岸领域, Action, Adventure, Casual  
4              2017  Log challenge, Otros, Action, Indie, Casual, S...  
...             ...                                                ...  
29970          2018  Colony on mars, Nikita "ghost_rus", Strategy, ...  
29971          2018  Logistical: south africa, Sacada, Strategy, In...  
29972          2018  Russian roads, Laush dmitriy sergeevich, Indie...  
29973          2017  Exit 2 - directions, Xropi,stev3ns, Indie, Cas...  
29974          2017  Maze run vr, Otros, Adventure, Indie, Action, ...  

[29975 rows x 8 columns]

In [16]:
# Calcularemos la similitud coseno
from sklearn.metrics.pairwise import cosine_similarity, linear_kernel

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer


- **CountVectorizer** : Retorna la frecuencia absoluta de cada término en un texto

- **TF-IDF**  Retorna la frecuencia de cada término en un término, y normaliza por el totoal de documentos donde el termino aparece

In [96]:
df.to_csv('06_recomendacion_juego.csv.gz', index=False,compression='gzip')

In [ ]:
df = steam_games[['steam_id','features']]
df['correlacion'] = 0

id = 2780.0

text_1 = df[df['steam_id'] == id]['features'].iloc[0]

## Vamos a extraer en una lista las n palabras más importantes
palabras_mas_relevantes = select_n_best(steam_genres,n)

def drop_not_important(genres):
  return(', ').join([palabra for palabra in genres.split(', ') if palabra.capitalize() in palabras_mas_relevantes])

steam_games['genres'] = steam_games['genres'].apply(drop_not_important)


cols_concatenate = ['app_name','developer','genres']

steam_games['features'] = steam_games[cols_concatenate].apply(lambda row: ', '.join(row), axis=1)

# Calcularemos la similitud coseno
from sklearn.metrics.pairwise import cosine_similarity, linear_kernel

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

df = steam_games[['steam_id','features']]



import nltk
from nltk.corpus import stopwords

#Eliminaremos las stopwords

stop_words_steams = ['op','based','co','first']
stop = list(stopwords.words('english'))
stop += stop_words_steams



def score_ml(text):
  data_corpus = [text_1, text]  
  tf = TfidfVectorizer(stop_words=stop)

  tf_idf_matrix_df =tf.fit_transform(data_corpus)
  
  return(linear_kernel(tf_idf_matrix_df,tf_idf_matrix_df)[0,1])

# prueba = df.head(1000)
# prueba['correlacion'] = prueba['features'].head(1000).apply(score_ml)

df['correlacion'] = df['features'].apply(score_ml)


In [134]:
df[1:6]

steam_id                                           features
1  643980.0  Ironbound, Secret level srl, Strategy, Indie, ...
2  670290.0  Real pool 3d - poolians, Poolians.com, Simulat...
3  767400.0           弹炸人2222, 彼岸领域, Action, Adventure, Casual
4  773570.0  Log challenge, Otros, Action, Indie, Casual, S...
5  772540.0  Battle royale trainer, Trickjump games ltd, Ac...

In [181]:
import os 
import pandas as pd

from sklearn.metrics.pairwise import cosine_similarity, linear_kernel

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

from nltk.corpus import stopwords

def endpoint6(id :int):
  path_endpoint_6 = os.path.join('..','data','clear','06_recomendacion_juego.csv.gz')
  df= pd.read_csv(path_endpoint_6).head(100)
  

  df['correlacion'] = 0

  text_1 = df[df['steam_id'] == id]['features'].iloc[0]


  #Eliminaremos las stopwords
  stop_words_steams = ['op','based','co','first']
  stop = list(stopwords.words('english'))
  stop += stop_words_steams

  def score_ml(text):
    data_corpus = [text_1, text]  
    tf = TfidfVectorizer(stop_words=stop)

    tf_idf_matrix_df =tf.fit_transform(data_corpus)
    
    return(linear_kernel(tf_idf_matrix_df,tf_idf_matrix_df)[0,1])

  df['correlacion'] = df['features'].apply(score_ml)
  
  df= df.sort_values('correlacion',ascending=False)[1:6]
  
  df['features'] = df['features'].apply(lambda x: x.split(',')[0])
  
  # texto = df.nlargest(5,'correlacion')[['features','correlacion']].to_dict(orient='records')  
  texto=df['features'].values
  return list(texto)
  

In [186]:
steam_games[steam_games['steam_id'] == 4780]

publisher  \
29759  Sega, feral interactive (mac), feral interacti...   

                                    genres                          app_name  \
29759  Strategy, Singleplayer, Multiplayer  Medieval ii: total war™ kingdoms   

       price  steam_id                                          developer  \
29759  11.99    4780.0  The creative assembly,feral interactive (mac),...   

       release_year                                           features  
29759          2007  Medieval ii: total war™ kingdoms, The creative...

In [182]:
endpoint6(2780.0)

['Battle royale trainer',
 "Garry's mod",
 'Tomb raider: anniversary',
 'The ship: murder party',
 'Spear of destiny']

In [88]:
df.sort_values('correlacion',ascending=False)

steam_id                                           features  \
98       2780.0  Arma: combat operations, Bohemia interactive, ...   
2637   304380.0  Arma 3 helicopters, Bohemia interactive, Simul...   
29576   33900.0  Arma 2, Bohemia interactive, Simulation, Actio...   
27966  107410.0  Arma 3, Bohemia interactive, Simulation, Multi...   
9606   639600.0  Arma 3 malden, Bohemia interactive, Action, Si...   
...         ...                                                ...   
15011  665590.0  Dog gone golfing, Vagabond dog, Sports, Casual...   
15012  694450.0                      Mclaren, Otros, Racing, Movie   
15017  646260.0  Fantasy grounds - death comes to stoneholme (p...   
15018  702040.0  Battle bruise — soundtrack, Zanardi and liza, ...   
14987  694190.0  Deluxe content - cossacks 3: the golden age, G...   

       correlacion  
98        1.000000  
2637      0.602975  
29576     0.510149  
27966     0.510149  
9606      0.505606  
...            ...  
15011     0.000000  
15012     0.000000  
15017     0.000000  
15018     0.000000  
14987     0.000000  

[29975 rows x 3 columns]

In [51]:
text_1

'Arma: combat operations, Bohemia interactive, Action, Simulation, Shooter'

In [81]:
prueba.nlargest(5,'correlacion')

steam_id                                           features  correlacion
98     2780.0  Arma: combat operations, Bohemia interactive, ...     1.000000
437   65700.0  Arma 2: british armed forces, Bohemia interact...     0.392181
667   65790.0  Arma: cold war assault, Bohemia interactive, S...     0.390066
846   65733.0  Take on helicopters: hinds, Bohemia interactiv...     0.279828
290   32770.0  Joint operations: combined arms gold, Novalogi...     0.216934

In [171]:
prueba.nlargest(5,'correlacion')

steam_id                                           features  correlacion
98     2780.0  Arma: combat operations, Bohemia interactive, ...     1.000000
437   65700.0  Arma 2: british armed forces, Bohemia interact...     0.450268
667   65790.0  Arma: cold war assault, Bohemia interactive, A...     0.450268
260   10130.0              Timeshift™, Saber interactive, Action     0.260556
285   35000.0                Mini ninjas, Io interactive, Action     0.225765

In [337]:
print(text1,'\n \n',text2,'\n\n',text3)

Puzzle station 15th anniversary retro release, Ninai games,yeaboing, Casual, Indie 
 
 Baseball riot, 10tons ltd, Casual, Indie, Action, Singleplayer 

 Doodle god blitz - world of magic dlc, Joybits ltd., Indie, Casual, Simulation


In [355]:
data_corpus = [text1, text2,text3]

## Ajustamos el modelo
X = count_vectorizer.fit_transform(data_corpus)

# contaremos cuantas veces se repite
print(X.toarray(),'\n',count_vectorizer.get_feature_names_out())

[[0 1 1 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 1 0 0 0 1 1 0]
 [1 0 0 1 0 0 0 1 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 1 0 1 0 0 1]
 [0 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0]] 
 ['2014' 'action' 'adventure' 'casual' 'clover' 'crimzon' 'delivery'
 'edition' 'found' 'francisco' 'friends' 'glory' 'ignition' 'indie' 'my'
 'new' 'otros' 'over' 'planning' 'remastered' 'rocksmith' 'san' 'service'
 'simulation' 'special' 'ubisoft' 'world' 'yotsubane' 'you']


In [356]:
import nltk
from nltk.corpus import stopwords

#Eliminaremos las stopwords

stop_words_steams = ['op','based','co','first']
stop = list(stopwords.words('english'))
stop += stop_words_steams

In [357]:
tf = TfidfVectorizer(stop_words=stop)

In [358]:
tf_idf_matrix_prueba =tf.fit_transform(data_corpus)

In [359]:
tf_idf_matrix = tf.fit_transform(steam_games['genres'])

In [360]:
tf_idf_matrix

<29975x8 sparse matrix of type '<class 'numpy.float64'>'
	with 69266 stored elements in Compressed Sparse Row format>

In [361]:
tf.get_feature_names_out()

array(['action', 'adventure', 'casual', 'indie', 'multiplayer',
       'simulation', 'singleplayer', 'strategy'], dtype=object)

### Similitud coseno

In [34]:
# tf_idf_matrix

<44044x358 sparse matrix of type '<class 'numpy.float64'>'
	with 929176 stored elements in Compressed Sparse Row format>

In [91]:
# calcularemos los features para cada (texto) utilizando el producto punto entre matrices

In [36]:
linear_kernel(tf_idf_matrix_prueba,tf_idf_matrix_prueba)

array([[1.        , 0.31125747],
       [0.31125747, 1.        ]])